### ISSUE TITLE
[RFC] Shoulder Gadgets

### ISSUE THREAD

**Issue by JaredWright** [Bareflank/shoulder#12]
After creating both a C and C++ header generator, it seems like there are quite a few parts shared between the two generators. Additionally, some of the generator functions (like ```_generate_bitfield_accessors()``` are large and complex, and could benefit from being broken down into smaller, bite-size pieces that are more easily understandable and testable individually.

This RFC proposes the addition of a new sub-package within Shoulder called ```gadget```. The gadget package will contain single-purpose generator "gadgets" that can be reused across all built-in shoulder generators, and also be used by external Python modules that want to use Shoulder.

The gadget package will follow a similar pattern to the generator package. An interface for each gadget will be defined using an AbstractGadget abstract-base class:

```
import abc

class AbstractGadget(abc.ABC):
    @property
    @abc.abstractmethod
    def description(self):
        """ Description of what this gadget does """

    @abc.abstractmethod
    def generate(self, objects, outfile):
        """ Generate a specfic output using the given Shoulder objects """
        """ to the given output file """
        return

    def __str__(self):
        return self.description
```

An example of a concrete gadget would be the following, a simple gadget to insert a license into a generated output:

```
from shoulder.gadget.abstract_gadget import AbstractGadget
from shoulder.logger import logger
from shoulder.config import config
from shoulder.exception import *

class LicenseGadget(AbstractGadget):
    @property
    def description(self):
        return "Generate the Shoulder license for a C/C++ file"

    def generate(self, objects, outfile):
        try:
            with open(config.license_template_path, "r") as license:
                for line in license:
                    outfile.write("// " + line)
                outfile.write("\n")

            msg = "{gadget}: license generated".format(
                gadget = str(type(self).__name__)
            )
            logger.debug(msg)

        except Exception as e:
            msg = "{gadget} failed to generate license: {exception}".format(
                gadget = str(type(self).__name__),
                exception = e
            )
            raise ShoulderGeneratorException(msg)

def generate(objects, outfile):
    g = LicenseGadget()
    g.generate(objects, outfile)
```

**Comment by JaredWright** [comment]
@JWZepf what do you think? Useful?

**Comment by JWZepf** [comment]
Yeah, I like the idea. There are a couple of things that are different between the C and C++ generators (`generate_register`, `generate_single_fieldset`, etc), so we would still need to define separate gadgets for both , but this would make it really easy to cover common ground between the two (license, includes, header guards, etc). It would also make it so changes would only have to be made in one place, making updating code a lot easier.

**Comment by JWZepf** [comment]
It would also have the benefit of breaking up the really large generator files, help with readability and modularity.
