### ISSUE TITLE
Decorator Based Gadgets

### ISSUE THREAD

**Issue by JaredWright** [Bareflank/shoulder#18]
RFC #12 introduced the concept of "gadgets" to shoulder with the intention of providing a way to break down complex Generator objects into smaller, more reusable bits and pieces. This gadget concept followed the same design pattern behind generators: An ```AbstractGadget``` class defined an interface that specific concrete gadgets would implement to provide their own functionality. This choice to use an abstract base class to define the gadget interface seems to be imposing some limitations:

* There isn't easy way to parametrize each gadget differently (which seems to be necessary)
* It is difficult to write a gadget that "wraps" content (like an include guard, or C++ namespace)
* It is a little awkward to call the gadgets from within a generator (the whole point of the gadget in the first place)

To overcome the above limitations, this RFC proposes to move the gadget concept into an implementation that utilizes [python decorators](https://realpython.com/primer-on-python-decorators/), instead of an abstract base class. This way, a shoulder generator could use a gadget by "decorating" its private, internal functions. Each decorator would optionally provide parameters for tweaking generated content. For example:

```
import os
import shoulder

class MyGenerator(shoulder.generator.abstract_generator.AbstractGenerator):
    def generate(self, objects, outpath):
        outfile_path = os.path.abspath(os.path.join(outpath, "my_generated_output.h"))

        with open(outfile_path, "w") as outfile:
            self._generate(objects, outfile)

    @shoulder.gadget.license
    @shoulder.gadget.include_guard(name="MY_CUSTOM_INCLUDE_GUARD_H")
    def _generate(self, objects, outfile):
        outfile.write("This decorated content will contain a license and be wrapped in include guards")
```

The example above applies two decorator-based gadgets named ```shoulder.gadget.license```, and ```shoulder.gadget.include_guard```. The implementation of the include_guard gadget would be the following:

```
def include_guard(_decorated=None, *, name="SHOULDER_AARCH64_H"):
    def _include_guard(decorated):
        def include_guard_decorator(generator, objects, outfile):
            outfile.write("#ifndef " + str(name) + "\n")
            outfile.write("#define " + str(name) + "\n\n")
            decorated(generator, objects, outfile)
            outfile.write("#endif\n")
        return include_guard_decorator

    if _decorated is None:
        return _include_guard
    else:
        return _include_guard(_decorated)
```

**Comment by JWZepf** [comment]
Ok, I think I understand how the decorators work now, that is a very useful tutorial you linked. Just to clarify, `decorated` is the function object defined below the `@` decorators (`_generate()` in the example)?

While decorators are a little weird at first, I think it makes a lot of sense to use them, especially with the ability to have elastic function arguments. We may sacrifice a little bit of readability, but the code is still pretty intuitive and the effectiveness far outweighs the small learning curve with decorators.

**Comment by JaredWright** [comment]
That is correct, ```decorated``` is the function that is "being decorated" (```_generate()``` in the example)

I 100% agree on losing some readability, that would be my main hesitation with trying out this pattern as well. I bet there's a way we could implement some sort of common template that could help hide the complexity of defining a new decorator. Open to suggestions!

**Comment by JWZepf** [comment]
I think as long as we are diligent with providing good documentation headers for the gadgets with  usage instructions like you have done in the recent PR we should be ok. The license and include guard gadgets are also simple enough to provide a good starting point for someone who wants to implement their own gadget.
