### ISSUE TITLE
Generator Modules

### ISSUE THREAD

**Issue by JaredWright** [Bareflank/shoulder#6]
This RFC proposes a design for generating outputs based on the results of parsed ASL/XML inputs (RFC #2).

## Overview

The overall goal of the Shoulder project is to generate output files that contain functions to manipulate system registers and execute system instructions on the aarch64 architecture. Generated files might include language specific header files, libraries, or tests that you could include into a larger software project. This RFC proposes a mechanism to add file generation support to the Shoulder project.

## Proposed Design

Generators for the Shoulder project will follow the same basic design pattern used for Shoulder parsers: an abstract base class will be created that represents the required interface that a generator must provide:

```
class AbstractGenerator(abc.ABC):
    @abc.abstractmethod
    def generate(self, objects, outpath):
        """ Generate target output using the given register and/or """
        """ instruction objects to a file at the given output path"""
        return
```

Concrete generators will then implement this interface. For this RFC, one generator will be implemented to create a C++ header file with intrinsic-like register access functions:

```
from shoulder.generator.abstract_generator import AbstractGenerator
from shoulder.logger import logger
from shoulder.config import config
from shoulder.exception import GeneratorException

class CxxHeaderGenerator(AbstractGenerator):
    def __init__(self):
        self._current_indent_level = 0

    def generate(self, objects, outpath):
        logger.info("Generating C++ header: " + str(outpath))
        with open(outpath, "w") as outfile:
            self._generate_license(outfile)
            self._generate_cxx_includes(outfile)
            self._generate_include_guard_open(outfile)
            self._generate_namespace_open(outfile)

            self._generate_objects(objects, outfile)

            self._generate_namespace_close(outfile)
            self._generate_include_guard_close(outfile)
```

All generators will be grouped into a submodule (subdirectory) of the Shoulder package at ```shoulder/generator/```.

## Out-of-scope:

Generator modules will *not* be responsible for validating the contents of the objects (registers and instructions) that they will generate. Generators will attempt to generate output files without any modifications to the given inputs. As a result, the generated output will be prone to any mistakes made by the parsers that created the list of objects to be generated. To address invalid registers and allow for the ability to exclude registers, a separate *filter module* RFC will be created as a next step.

**Comment by connojd** [comment]
Looks good, I just had one question: will concrete classes just look at all the others to make a unique ID, or will some script/config be used?

**Comment by JaredWright** [comment]
I might actually just get rid of the id attribute all together and use the module's name (the file name) as the id. Then the interface would just require you to provide a generate function.

Configs will be used later (I have a future RFC for that) to decide which generators get used.

**Comment by JaredWright** [comment]
Updated the design above to not include the generator_id attribute. Will have a PR for this ready shortly!
